services:
  poke-planner:
    image: ghcr.io/kardam00n/pokeplanner:latest
    container_name: poke-planner
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # - APP_MODE=server
      # - DATA_PATH=/app/data
    # volumes:
    #   - ./data:/app/data
